excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
disabled_rules:
  - type_name
  - empty_count
  - file_header
  - force_try
  - block_based_kvo
  - discarded_notification_center_observer
  - explicit_type_interface
  - file_length
  - implicit_getter
  - implicitly_unwrapped_optional
  - leading_whitespace
  - let_var_whitespace
  - notification_center_detachment
  - private_over_fileprivate
  - sorted_imports
  - strict_fileprivate
  - todo
  - trailing_closure
  - trailing_whitespace
  - type_body_length
  - valid_ibinspectable
  - unused_optional_binding
  - nesting
  - force_cast
  - large_tuple
  - legacy_hashing
  - identifier_name
  
opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - empty_count
  - explicit_init
  - extension_access_modifier
  - fatal_error_message
  - file_header
  - first_where
  - force_unwrapping
  - joined_default_parameter
  - literal_expression_end_indentation
  - multiline_parameters
  - operator_usage_whitespace
  - override_in_extension
  - private_outlet
  - redundant_nil_coalescing
  - sorted_first_last
  - switch_case_on_newline
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

line_length:
  - 200 #warning
  - 350 #error

cyclomatic_complexity:
 # - 15 #warning
  #- 20 #error
  - 150

function_parameter_count:
  - 6 #warning

function_body_length:
 - 150

identifier_name:
  min_length: 3 #warning
  max_length: #warning or error
    warning: 40
    error: 50
